language: node_js
node_js:
  - '0.11'
before_install:
  - npm install -g grunt-cli
  - npm install
script:
  - grunt build
  - ./travis/deploy-if-master.sh
notifications:
  email:
    - john-github@rmdashrf.org
